# Generated by Django 4.1.7 on 2023-03-23 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrapp', '0003_alter_review_user_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
