# Generated by Django 4.1.7 on 2023-03-23 05:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mrapp', '0004_review_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='downvoted_users',
            field=models.ManyToManyField(related_name='downvoted_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='upvoted_users',
            field=models.ManyToManyField(related_name='upvoted_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
